use_frameworks!

platform :ios, '8.0'

target 'YLNetClient_Example' do
  pod 'YLNetClient', :path => '../'

  target 'YLNetClient_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
