use_frameworks!
inhibit_all_warnings!
platform :ios, '8.0'

target 'YLNetClient_Example' do
  pod 'YLNetClient', :path => '../'

  pod 'AFNetworking'
  pod 'YLJsonLib'
  pod 'MBProgressHUD'
  
  target 'YLNetClient_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase'
  end
end
